DATASETS = ['megabird_richness_eoagrid_eu',
            'megafauna_union',
            'megamammal_richness_cgrs_eu']

rule all:
  input:
    "data/megafauna_sp.csv",
    expand("data/megafauna/{dataset}.{ext}", dataset=DATASETS,
           ext=['dbf', 'prj', 'shp', 'shx'])

# Rule to extract the data from from the zip archive.
rule extract:
    input:
        "data/org/Archive.zip"
    output:
        dir="data/megafauna",
        dst_spatial=expand("data/megafauna/{dataset}.{ext}", dataset=DATASETS,
                           ext=['dbf', 'prj', 'shp', 'shx'])
    log:
        "log/extract.log"
    message: "Extracting shapefiles from {input}."
    shell:
        # Extra quotes needed because of potential whitespace in the name.
        "unzip -o '{input}' -d {output.dir} >& {log} && touch -c {output.dst_spatial}"

# Rule convert the Excel file containing the spcies names in CSV.
rule spconvert:
    input:
        "data/org/megafauna_sp.xlsx"
    output:
        "data/megafauna_sp.csv"
    log:
        "log/spconvert.log"
    message: "converting {input} to CSV."
    script:
        "scripts/spconvert.py"
